<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        $this->roles();
        $this->countries();
    }

    private function roles(): void
    {
        DB::unprepared("INSERT INTO `roles` (`title`)
            VALUES
            ('admin'), ('manager'), ('waiter');");
    }

    private function countries(): void
    {
        DB::unprepared("INSERT INTO `countries` (`id`, `name`, `timezone`, `code`)
            VALUES
            (2, 'Andorra', 'Europe/Andorra', 'AD'),
                (3, 'United Arab Emirates', 'Asia/Dubai', 'AE'),
                (4, 'Afghanistan', 'Asia/Kabul', 'AF'),
                (5, 'Antigua and Barbuda', 'America/Antigua', 'AG'),
                (6, 'Anguilla', 'America/Anguilla', 'AI'),
                (7, 'Albania', 'Europe/Tirane', 'AL'),
                (8, 'Armenia', 'Asia/Yerevan', 'AM'),
                (9, 'Netherlands Antilles', 'America/Curacao', 'AN'),
                (10, 'Angola', 'Africa/Luanda', 'AO'),
                (11, 'Antarctica', 'Antarctica/McMurdo', 'AQ'),
                (12, 'Argentina', 'America/Argentina/Buenos_Aires', 'AR'),
                (13, 'American Samoa', 'Pacific/Pago_Pago', 'AS'),
                (14, 'Austria', 'Europe/Vienna', 'AT'),
                (15, 'Australia', 'Australia/Sydney', 'AU'),
                (16, 'Aruba', 'America/Aruba', 'AW'),
                (17, 'Azerbaijan', 'Asia/Baku', 'AZ'),
                (18, 'Bosnia and Herzegovina', 'Europe/Sarajevo', 'BA'),
                (19, 'Barbados', 'America/Barbados', 'BB'),
                (20, 'Bangladesh', 'Asia/Dhaka', 'BD'),
                (21, 'Belgium', 'Europe/Brussels', 'BE'),
                (22, 'Burkina Faso', 'Africa/Ouagadougou', 'BF'),
                (23, 'Bulgaria', 'Europe/Sofia', 'BG'),
                (24, 'Bahrain', 'Asia/Bahrain', 'BH'),
                (25, 'Burundi', 'Africa/Bujumbura', 'BI'),
                (26, 'Benin', 'Africa/Porto-Novo', 'BJ'),
                (27, 'Bermuda', 'Atlantic/Bermuda', 'BM'),
                (28, 'Brunei', 'Asia/Brunei', 'BN'),
                (29, 'Bolivia', 'America/La_Paz', 'BO'),
                (30, 'Brazil', 'America/Sao_Paulo', 'BR'),
                (31, 'Bahamas', 'America/Nassau', 'BS'),
                (32, 'Bhutan', 'Asia/Thimphu', 'BT'),
                (33, 'Bouvet Island', 'Antarctica/Bouvet', 'BV'),
                (34, 'Botswana', 'Africa/Gaborone', 'BW'),
                (35, 'Belarus', 'Europe/Minsk', 'BY'),
                (36, 'Belize', 'America/Belize', 'BZ'),
                (37, 'Canada', 'America/Toronto', 'CA'),
                (38, 'Cocos [Keeling] Islands', 'Indian/Cocos', 'CC'),
                (39, 'Congo [DRC]', 'Africa/Kinshasa', 'CD'),
                (40, 'Central African Republic', 'Africa/Bangui', 'CF'),
                (41, 'Congo [Republic]', 'Africa/Brazzaville', 'CG'),
                (42, 'Switzerland', 'Europe/Zurich', 'CH'),
                (43, 'Côte d\'Ivoire', 'Africa/Abidjan', 'CI'),
                (44, 'Cook Islands', 'Pacific/Rarotonga', 'CK'),
                (45, 'Chile', 'America/Santiago', 'CL'),
                (46, 'Cameroon', 'Africa/Douala', 'CM'),
                (47, 'China', 'Asia/Shanghai', 'CN'),
                (48, 'Colombia', 'America/Bogota', 'CO'),
                (49, 'Costa Rica', 'America/Costa_Rica', 'CR'),
                (50, 'Cuba', 'America/Havana', 'CU'),
                (51, 'Cape Verde', 'Atlantic/Cape_Verde', 'CV'),
                (52, 'Christmas Island', 'Indian/Christmas', 'CX'),
                (53, 'Cyprus', 'Asia/Nicosia', 'CY'),
                (54, 'Czech Republic', 'Europe/Prague', 'CZ'),
                (55, 'Germany', 'Europe/Berlin', 'DE'),
                (56, 'Djibouti', 'Africa/Djibouti', 'DJ'),
                (57, 'Denmark', 'Europe/Copenhagen', 'DK'),
                (58, 'Dominica', 'America/Dominica', 'DM'),
                (59, 'Dominican Republic', 'America/Santo_Domingo', 'DO'),
                (60, 'Algeria', 'Africa/Algiers', 'DZ'),
                (61, 'Ecuador', 'America/Guayaquil', 'EC'),
                (62, 'Estonia', 'Europe/Tallinn', 'EE'),
                (63, 'Egypt', 'Africa/Cairo', 'EG'),
                (64, 'Western Sahara', 'Africa/El_Aaiun', 'EH'),
                (65, 'Eritrea', 'Africa/Asmara', 'ER'),
                (66, 'Spain', 'Europe/Madrid', 'ES'),
                (67, 'Ethiopia', 'Africa/Addis_Ababa', 'ET'),
                (68, 'Finland', 'Europe/Helsinki', 'FI'),
                (69, 'Fiji', 'Pacific/Fiji', 'FJ'),
                (70, 'Falkland Islands [Islas Malvinas]', 'Atlantic/Stanley', 'FK'),
                (71, 'Micronesia', 'Pacific/Chuuk', 'FM'),
                (72, 'Faroe Islands', 'Atlantic/Faroe', 'FO'),
                (73, 'France', 'Europe/Paris', 'FR'),
                (74, 'Gabon', 'Africa/Libreville', 'GA'),
                (75, 'United Kingdom', 'Europe/London', 'GB'),
                (76, 'Grenada', 'America/Grenada', 'GD'),
                (77, 'Georgia', 'Asia/Tbilisi', 'GE'),
                (78, 'French Guiana', 'America/Cayenne', 'GF'),
                (79, 'Guernsey', 'Europe/Guernsey', 'GG'),
                (80, 'Ghana', 'Africa/Accra', 'GH'),
                (81, 'Gibraltar', 'Europe/Gibraltar', 'GI'),
                (82, 'Greenland', 'America/Godthab', 'GL'),
                (83, 'Gambia', 'Africa/Banjul', 'GM'),
                (84, 'Guinea', 'Africa/Conakry', 'GN'),
                (85, 'Guadeloupe', 'America/Guadeloupe', 'GP'),
                (86, 'Equatorial Guinea', 'Africa/Malabo', 'GQ'),
                (87, 'Greece', 'Europe/Athens', 'GR'),
                (88, 'South Georgia and the South Sandwich Islands', 'Atlantic/South_Georgia', 'GS'),
                (89, 'Guatemala', 'America/Guatemala', 'GT'),
                (90, 'Guam', 'Pacific/Guam', 'GU'),
                (91, 'Guinea-Bissau', 'Africa/Bissau', 'GW'),
                (92, 'Guyana', 'America/Guyana', 'GY'),
                (93, 'Gaza Strip', 'Asia/Gaza', 'PS'),
                (94, 'Hong Kong', 'Asia/Hong_Kong', 'HK'),
                (95, 'Heard Island and McDonald Islands', 'Indian/Kerguelen', 'HM'),
                (96, 'Honduras', 'America/Tegucigalpa', 'HN'),
                (97, 'Croatia', 'Europe/Zagreb', 'HR'),
                (98, 'Haiti', 'America/Port-au-Prince', 'HT'),
                (99, 'Hungary', 'Europe/Budapest', 'HU'),
                (100, 'Indonesia', 'Asia/Jakarta', 'ID'),
                (101, 'Ireland', 'Europe/Dublin', 'IE'),
                (102, 'Israel', 'Asia/Jerusalem', 'IL'),
                (103, 'Isle of Man', 'Europe/Isle_of_Man', 'IM'),
                (104, 'India', 'Asia/Kolkata', 'IN'),
                (105, 'British Indian Ocean Territory', 'Indian/Chagos', 'IO'),
                (106, 'Iraq', 'Asia/Baghdad', 'IQ'),
                (107, 'Iran', 'Asia/Tehran', 'IR'),
                (108, 'Iceland', 'Atlantic/Reykjavik', 'IS'),
                (109, 'Italy', 'Europe/Rome', 'IT'),
                (110, 'Jersey', 'Europe/Jersey', 'JE'),
                (111, 'Jamaica', 'America/Jamaica', 'JM'),
                (112, 'Jordan', 'Asia/Amman', 'JO'),
                (113, 'Japan', 'Asia/Tokyo', 'JP'),
                (114, 'Kenya', 'Africa/Nairobi', 'KE'),
                (115, 'Kyrgyzstan', 'Asia/Bishkek', 'KG'),
                (116, 'Cambodia', 'Asia/Phnom_Penh', 'KH'),
                (117, 'Kiribati', 'Pacific/Tarawa', 'KI'),
                (118, 'Comoros', 'Indian/Comoro', 'KM'),
                (119, 'Saint Kitts and Nevis', 'America/St_Kitts', 'KN'),
                (120, 'North Korea', 'Asia/Pyongyang', 'KP'),
                (121, 'South Korea', 'Asia/Seoul', 'KR'),
                (122, 'Kuwait', 'Asia/Kuwait', 'KW'),
                (123, 'Cayman Islands', 'America/Cayman', 'KY'),
                (124, 'Kazakhstan', 'Asia/Almaty', 'KZ'),
                (125, 'Laos', 'Asia/Vientiane', 'LA'),
                (126, 'Lebanon', 'Asia/Beirut', 'LB'),
                (127, 'Saint Lucia', 'America/St_Lucia', 'LC'),
                (128, 'Liechtenstein', 'Europe/Vaduz', 'LI'),
                (129, 'Sri Lanka', 'Asia/Colombo', 'LK'),
                (130, 'Liberia', 'Africa/Monrovia', 'LR'),
                (131, 'Lesotho', 'Africa/Maseru', 'LS'),
                (132, 'Lithuania', 'Europe/Vilnius', 'LT'),
                (133, 'Luxembourg', 'Europe/Luxembourg', 'LU'),
                (134, 'Latvia', 'Europe/Riga', 'LV'),
                (135, 'Libya', 'Africa/Tripoli', 'LY'),
                (136, 'Morocco', 'Africa/Casablanca', 'MA'),
                (137, 'Monaco', 'Europe/Monaco', 'MC'),
                (138, 'Moldova', 'Europe/Chisinau', 'MD'),
                (139, 'Montenegro', 'Europe/Podgorica', 'ME'),
                (140, 'Madagascar', 'Indian/Antananarivo', 'MG'),
                (141, 'Marshall Islands', 'Pacific/Majuro', 'MH'),
                (142, 'Macedonia [FYROM]', 'Europe/Skopje', 'MK'),
                (143, 'Mali', 'Africa/Bamako', 'ML'),
                (144, 'Myanmar [Burma]', 'Asia/Yangon', 'MM'),
                (145, 'Mongolia', 'Asia/Ulaanbaatar', 'MN'),
                (146, 'Macau', 'Asia/Macau', 'MO'),
                (147, 'Northern Mariana Islands', 'Pacific/Saipan', 'MP'),
                (148, 'Martinique', 'America/Martinique', 'MQ'),
                (149, 'Mauritania', 'Africa/Nouakchott', 'MR'),
                (150, 'Montserrat', 'America/Montserrat', 'MS'),
                (151, 'Malta', 'Europe/Malta', 'MT'),
                (152, 'Mauritius', 'Indian/Mauritius', 'MU'),
                (153, 'Maldives', 'Indian/Maldives', 'MV'),
                (154, 'Malawi', 'Africa/Blantyre', 'MW'),
                (155, 'Mexico', 'America/Mexico_City', 'MX'),
                (156, 'Malaysia', 'Asia/Kuala_Lumpur', 'MY'),
                (157, 'Mozambique', 'Africa/Maputo', 'MZ'),
                (158, 'Namibia', 'Africa/Windhoek', 'NA'),
                (159, 'New Caledonia', 'Pacific/Noumea', 'NC'),
                (160, 'Niger', 'Africa/Niamey', 'NE'),
                (161, 'Norfolk Island', 'Pacific/Norfolk', 'NF'),
                (162, 'Nigeria', 'Africa/Lagos', 'NG'),
                (163, 'Nicaragua', 'America/Managua', 'NI'),
                (164, 'Netherlands', 'Europe/Amsterdam', 'NL'),
                (165, 'Norway', 'Europe/Oslo', 'NO'),
                (166, 'Nepal', 'Asia/Kathmandu', 'NP'),
                (167, 'Nauru', 'Pacific/Nauru', 'NR'),
                (168, 'Niue', 'Pacific/Niue', 'NU'),
                (169, 'New Zealand', 'Pacific/Auckland', 'NZ'),
                (170, 'Oman', 'Asia/Muscat', 'OM'),
                (171, 'Panama', 'America/Panama', 'PA'),
                (172, 'Peru', 'America/Lima', 'PE'),
                (173, 'French Polynesia', 'Pacific/Tahiti', 'PF'),
                (174, 'Papua New Guinea', 'Pacific/Port_Moresby', 'PG'),
                (175, 'Philippines', 'Asia/Manila', 'PH'),
                (176, 'Pakistan', 'Asia/Karachi', 'PK'),
                (177, 'Poland', 'Europe/Warsaw', 'PL'),
                (178, 'Saint Pierre and Miquelon', 'America/Miquelon', 'PM'),
                (179, 'Pitcairn Islands', 'Pacific/Pitcairn', 'PN'),
                (180, 'Puerto Rico', 'America/Puerto_Rico', 'PR'),
                (181, 'Palestinian Territories', 'Asia/Hebron', 'PS'),
                (182, 'Portugal', 'Europe/Lisbon', 'PT'),
                (183, 'Palau', 'Pacific/Palau', 'PW'),
                (184, 'Paraguay', 'America/Asuncion', 'PY'),
                (185, 'Qatar', 'Asia/Qatar', 'QA'),
                (186, 'Réunion', 'Indian/Reunion', 'RE'),
                (187, 'Romania', 'Europe/Bucharest', 'RO'),
                (188, 'Serbia', 'Europe/Belgrade', 'RS'),
                (189, 'Russia', 'Europe/Moscow', 'RU'),
                (190, 'Rwanda', 'Africa/Kigali', 'RW'),
                (191, 'Saudi Arabia', 'Asia/Riyadh', 'SA'),
                (192, 'Solomon Islands', 'Pacific/Guadalcanal', 'SB'),
                (193, 'Seychelles', 'Indian/Mahe', 'SC'),
                (194, 'Sudan', 'Africa/Khartoum', 'SD'),
                (195, 'Sweden', 'Europe/Stockholm', 'SE'),
                (196, 'Singapore', 'Asia/Singapore', 'SG'),
                (197, 'Saint Helena', 'Atlantic/St_Helena', 'SH'),
                (198, 'Slovenia', 'Europe/Ljubljana', 'SI'),
                (199, 'Svalbard and Jan Mayen', 'Arctic/Longyearbyen', 'SJ'),
                (200, 'Slovakia', 'Europe/Bratislava', 'SK'),
                (201, 'Sierra Leone', 'Africa/Freetown', 'SL'),
                (202, 'San Marino', 'Europe/San_Marino', 'SM'),
                (203, 'Senegal', 'Africa/Dakar', 'SN'),
                (204, 'Somalia', 'Africa/Mogadishu', 'SO'),
                (205, 'Suriname', 'America/Paramaribo', 'SR'),
                (206, 'São Tomé and Príncipe', 'Africa/Sao_Tome', 'ST'),
                (207, 'El Salvador', 'America/El_Salvador', 'SV'),
                (208, 'Syria', 'Asia/Damascus', 'SY'),
                (209, 'Swaziland', 'Africa/Mbabane', 'SZ'),
                (210, 'Turks and Caicos Islands', 'America/Grand_Turk', 'TC'),
                (211, 'Chad', 'Africa/Ndjamena', 'TD'),
                (212, 'French Southern Territories', 'Indian/Kerguelen', 'TF'),
                (213, 'Togo', 'Africa/Lome', 'TG'),
                (214, 'Thailand', 'Asia/Bangkok', 'TH'),
                (215, 'Tajikistan', 'Asia/Dushanbe', 'TJ'),
                (216, 'Tokelau', 'Pacific/Fakaofo', 'TK'),
                (217, 'Timor-Leste', 'Asia/Dili', 'TL'),
                (218, 'Turkmenistan', 'Asia/Ashgabat', 'TM'),
                (219, 'Tunisia', 'Africa/Tunis', 'TN'),
                (220, 'Tonga', 'Pacific/Tongatapu', 'TO'),
                (221, 'Turkey', 'Europe/Istanbul', 'TR'),
                (222, 'Trinidad and Tobago', 'America/Port_of_Spain', 'TT'),
                (223, 'Tuvalu', 'Pacific/Funafuti', 'TV'),
                (224, 'Taiwan', 'Asia/Taipei', 'TW'),
                (225, 'Tanzania', 'Africa/Dar_es_Salaam', 'TZ'),
                (226, 'Ukraine', 'Europe/Kyiv', 'UA'),
                (227, 'Uganda', 'Africa/Kampala', 'UG'),
                (228, 'U.S. Minor Outlying Islands', 'Pacific/Midway', 'UM'),
                (229, 'United States', 'America/New_York', 'US'),
                (230, 'Uruguay', 'America/Montevideo', 'UY'),
                (231, 'Uzbekistan', 'Asia/Tashkent', 'UZ'),
                (232, 'Vatican City', 'Europe/Vatican', 'VA'),
                (233, 'Saint Vincent and the Grenadines', 'America/St_Vincent', 'VC'),
                (234, 'Venezuela', 'America/Caracas', 'VE'),
                (235, 'British Virgin Islands', 'America/Tortola', 'VG'),
                (236, 'U.S. Virgin Islands', 'America/St_Thomas', 'VI'),
                (237, 'Vietnam', 'Asia/Ho_Chi_Minh', 'VN'),
                (238, 'Vanuatu', 'Pacific/Efate', 'VU'),
                (239, 'Wallis and Futuna', 'Pacific/Wallis', 'WF'),
                (240, 'Samoa', 'Pacific/Apia', 'WS'),
                (241, 'Kosovo', 'Europe/Belgrade', 'XK'),
                (242, 'Yemen', 'Asia/Aden', 'YE'),
                (243, 'Mayotte', 'Indian/Mayotte', 'YT'),
                (244, 'South Africa', 'Africa/Johannesburg', 'ZA'),
                (245, 'Zambia', 'Africa/Lusaka', 'ZM'),
                (246, 'Zimbabwe', 'Africa/Harare', 'ZW');");
    }
}
