import React, {Suspense, useState, useEffect} from 'react';
import ReactDOM from 'react-dom';
import './../i18nextConf';
import "./App.scss";

import LoadingPage from "../components/LoadingPage";
import bg from '../../assets/feedback-bg.jpg'
import ellipse from '../../assets/ellipse.png'
import plate from '../../assets/plate-1.png'

function App() {

  return (
    <Suspense fallback={<LoadingPage/>}>
      <div className="feedback">
        <div className="feedback-hero" style={{backgroundImage: `url(${bg})`}}>
          <h1 className="feedback-title feedback-hero-title">Terms of use</h1>
          <p className="feedback-text"></p>
        </div>
        <div className="feedback-main">
          <img src={ellipse} alt="ellipse" className='feedback-ellipse-1' />
          <img src={ellipse} alt="ellipse" className='feedback-ellipse-2' />
          <img src={plate} alt="plate" className='feedback-plate' />
          <div className="terms_container">
            <h3>Chapter I</h3>
            <h2 className="feedback-title">Introduction</h2>
            <p>Nubisreservation is provided as a service of Nubisreservation.com ApS. For the purposes hereof, Nubisreservation and Nubisreservation.com ApS are collectively referred to as the “Company” or “Nubisreservation”.</p>
            <p>The Company provides an online web application for restaurant owners who have registered with and paid a fee to the Company (each, a “Restaurant”) to manage reservations, table inventory, and guest contact information from a web-enabled device and to provide restaurant consumers (each, a “Guest”) with a fast, friendly way to search and reserve tables from a web-enabled device. The Company does not sell any products and is not a party to any transaction or any agreement a Guest may make with a Restaurant with regard to any food, product or service offered by such Restaurant.</p>
            <p>All users, whether a Guest, Restaurant or any other party, of the WebSites (each, a “User”), including, but not limited to, vendors who request an Account (“Account” or “Accounts”) are subject to the following terms of service (“Terms of Service”) and the privacy policy located at https://www.nubisreservation.com/privacy (the “Privacy Policy”).</p>
            <p>The Company reserves the right to update and change the Terms of Service and the Privacy Policy from time to time without notice. Any features added to the current Accounts, including the release of new and updated features (the “Changes”), shall be subject to the Terms of Service. Continued use of an Account after any Changes shall constitute consent to such Changes.</p>

            <h3>Chapter II</h3>
            <h2 className="feedback-title">Account Terms</h2>
            <p>To access certain functions of the WebSites, you must register as a unique User by providing certain current, complete, and accurate information about yourself. As part of the registration process, you will select a password and provide a valid email address as a User ID. You also have to give us certain registration information, all of which must be accurate and updated. You may not (i) select or use a User ID of another person with the intent to impersonate that person; (ii) use a User ID in which another person has rights without such person’s authorisation; or (iii) use a User ID that the Company, in its sole discretion, deems offensive. Failure to provide any requested information may delay or prevent the creation of an Account. You represent that: (a) the information you submit is truthful and accurate and that you have not misrepresented your identity; (b) you will update your contact information if it changes so that we can contact you; (c) your use of the WebSites and your use of services available on the WebSites do not violate any applicable law or regulation; (d) you are 18 years of age or older. Failure to comply with the foregoing shall constitute a breach of this Agreement, which may result in immediate termination of your Account. You shall be responsible for maintaining the confidentiality of your password.</p>
            <p>You shall notify the Company of any known or suspected unauthorised use(s) of your Account, or any known or suspected breach of security, including loss, theft, or unauthorised disclosure of your password or other information.</p>
            <p>You are responsible for maintaining the security of your password. The Company is not liable for any loss that you may suffer through the use of your password by others. You agree to notify the Company immediately of any unauthorised use of your Account or of any other breach of security known to you with respect to the WebSites or your Account. You agree to report any violations of this Agreement by others to the Company.</p>
            <p>You are responsible for all usage or activity on your Account, including use of the account by any third party authorised by you to use your User ID and password. Any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your account, at the Company’s sole discretion, and the Company may refer you to appropriate law enforcement agencies. Accounts may be issued to individuals who are 18 years of age or older, who are not under any legal disability and who agree to abide by these Terms of Service and the Privacy Policy. Accounts not meeting these requirements will be terminated. Accounts registered by “bots” or other automated methods are not permitted and will be deleted.</p>
            <p>The Company does not sell, license or endorse any of the Restaurants participating or listed on the WebSites and does not act as an agent of sale or an agent of any merchant or provider of food, products or services. The Company does not have and will not assume any responsibility for, or liability related to, any food, products and services offered, sold or provided by the Restaurants participating or listed on the WebSites. You should direct any questions, complaints or claims related to any food, product or service to the appropriate Restaurant.</p>
            <p>The Company does not warrant that products or descriptions, or any other content of the WebSites is accurate, complete, reliable, current or error-free. WebSite content is provided for informational purposes only and the Company shall have no liability for inaccuracy or incompleteness in product or service content, user ratings or commentary, or other content on the WebSites. The Company is not responsible or liable for any food, products, services, information or other materials displayed, purchased, or obtained by a Guest from the Restaurant or the WebSites. The Company does not endorse, warrant or guarantee the food, products or services of any Restaurant, including, without limitation, any prices, promotions, programs, policies, services, or other information posted by any Restaurant.</p>
            <p>The Company is not liable for any delays, inaccuracies, errors or omissions with respect to the information or the transmission or delivery of all or any part thereof, for any damage arising therefrom or occasioned thereby, or for the results obtained from the use of the information. The Company is not liable for any acts or omission of acts o Nubisreservation or any Restaurant on the WebSites. You assume the entire risk as to the accuracy, adequacy, completeness, currency, validity and quality of any information relating to the food, products or services provided to you by a Restaurant.</p>
            <p>Any information on the WebSites can change without notice.</p>
            <p>Nubisreservation assumes no liability, obligation or responsibility in connection with any transactions between a Guest and any Restaurant(s), including, but not limited to, failure by either party to keep a reservation, a Restaurant’s knowledge (or lack thereof) of any Guest’s food allergies, injuries and/or damages sustained or caused by a Guest at a Restaurant, a Guest’s or any employee’s behaviour at a Restaurant or the quality of the food, service and products at a Restaurant. If a Guest has a dispute with a Restaurant or any third party, all parties release the Company (and its agents and employees) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such dispute.</p>
            <p>Nubisreservation may send email or SMS confirmations on behalf of restaurants to confirm or follow up on reservations or to request a review or follow up feedback. Nubisreservation has the right to append at the bottom of any such email confirmations, and you consent to the placement of, a small branded advertising logo (hyper-linked) promoting Nubisreservation or a Nubisreservation partner business or website, this logo to be no larger than 800 pixels by 160 pixels.</p>
            <p>The Services may permit Guests to submit reviews, comments, and ratings, send emails and other communications; and submit suggestions, ideas, comments, questions, or other information for publication and distribution to restaurants and other third parties (“User Content”). Any such User Content must not be illegal, threatening, obscene, racist, defamatory, libellous, pornographic, infringing of intellectual property rights, promoting of illegal activity or harm to groups and/or individuals, invasive of privacy, purposely false or otherwise injurious to third parties or objectionable and must not consist of or contain software, computer viruses, commercial solicitation, political campaigning, chain letters, mass mailings, any form of “spam” or references to illegal activity, malpractice, purposeful overcharging, false advertising or health code violations (e.g. foreign objects in food, food poisoning, etc.). Guests may not use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of User Content. Nubisreservation reserves the right (but has no obligation) to monitor, remove, or edit User Content in Nubisreservation’s sole discretion, including if User Content violates any Nubisreservation Policies, but please note that Nubisreservation may or may not regularly review submitted User Content. Nubisreservation takes no responsibility and assumes no liability for any User Content submitted by any User or third party.</p>

            <h3>Chapter III</h3>
            <h2 className="feedback-title">Links to Other Websites</h2>
            <p>The WebSites may provide links to third-party web sites (“Third-Party Websites”). This Terms of Service Agreement governs only these WebSites and not any Third-Party Websites. The Company’s decision to link to a Third-Party Website is not an endorsement of the content or services in that linked Third-Party Website. The Company may not own or operate the Third-Party Website, and it has not reviewed, and cannot review, all of the material, including goods or services, made available through Third-Party Websites. The Company expressly disclaims any responsibility for the content, the accuracy of the information and any products or services available on the Third-Party Websites. If you decide to access linked Third-Party Websites, you do so at your own risk.</p>
            <p>The Company reserves the right and the Users agree that any information in an Account designated as “Public” may be used by the Company for promotional uses. External search engines may also index such Public information.</p>
            <p>Use of an Account does not grant a User a license to any software contained in, or used by, the Account. Users agree not to, directly or indirectly: reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of, or found at, or through, the Account or any software, documentation, or data related to the Account; remove any proprietary notices or labels from the Account or any Software, modify, translate, or create derivative works based on the Account or any Software; or copy, distribute, pledge, assign, or otherwise transfer or encumber rights to the Account or any Software. The Account shall be used for a User’s business or personal purposes only, as the case may be, and a User shall not use the Account or any Software for timesharing or service bureau purposes or otherwise for the benefit of a third party. If a User is using the Account in any country in the European Community, the prohibition against modifying, translating, reverse engineering, decompiling, disassembling or creating derivative works based on the Services or the Software does not affect a User’s rights under any legislation implementing the E.C. Council Directive on the Legal Protection of Computer Programs.</p>

            <h3>Chapter IV</h3>
            <h2 className="feedback-title">Portals / Restaurant Directories</h2>
            <p>Nubisreservation is happy to provide its reservation API to directories and portals to enable real-time bookings into Nubisreservation Restaurant Accounts, on the understanding that such directory or portal partners never place their or any affiliate company or entity’s version of a branded widget or API interface on a restaurant’s own website, in which case access to the Nubisreservation reservation API may be withdrawn at Nubisreservation’s absolute discretion.</p>
            <p>All branded widgets and API’s using the Nubisreservation widget or API must be branded as “Powered by Nubisreservation”.</p>
            <p>Nubisreservation may provide its partners with API access/widgets to Restaurant Accounts in instances where the partner acts as a complimentary booking channel. The same applies to partners that offer a complimentary trial period in their offering. Once the trial period has ended, Restaurant Accounts that would like to continue receiving bookings from the partner, will have the opportunity to do so by instructing the partner directly or by contacting Nubisreservation. If the latter has not been instructed, Restaurant Accounts will be automatically removed from the partner’s website/portal once the trial has ended.</p>

            <h4 className="feedback-sub_title">Online Booking Links from Restaurant Websites</h4>
            <p>Restaurant customers of Nubisreservation using Nubisreservation as their back-office table management system and which take online bookings from their Restaurant website agree to solely use the Nubisreservation booking widget or API or re-direct to the restaurant microsite page on app.Nubisreservation.com.</p>
            <p>The implementation of a.n.other booking system widget on a Restaurant website will be considered a breach of contract and will lead to immediate cessation of supply and removal of access to the Restaurant back-office account in Nubisreservation unless the position is rectified.</p>

            <h4 className="feedback-sub_title">Intellectual Property</h4>
            <p>The Users acknowledge and agree that any and all Company or Restaurant names and logos related to the Account and the Company or Restaurant and all related product and service names, design marks and slogans, are the property of the Company, the Restaurant or their affiliates or suppliers, as the case may be (collectively, the “Marks”). By agreeing to these Terms of Service, the Users agree not to use any of the Marks in any advertising, publicity or any other commercial manner without the prior written consent of the Company or the applicable Restaurant. The Users have no title or ownership in the Account, the Software or the Marks (other than their own Marks) and no other rights in the Account, the Software or the Marks. All ownership rights remain in the Company, the Restaurant or their third party suppliers, as the case may be. The Users agree to comply with all intellectual property laws and shall not encumber any interest in, or assert any rights to, the Marks (other than their own). The User may not reverse engineer, reverse assemble, decompile or disassemble, reproduce, modify, transmit, participate in the sale or transfer of, or create derivative works based on any Marks, in whole or in part.</p>
            <p>By registering and paying for an Account, each Restaurant agrees and grants the Company the right to use for these WebSites and other related purposes, all images, menus, logos, content and other information that may be found on the Restaurant’s own web sites.</p>

            <h3>Chapter V</h3>
            <h2 className="feedback-title">Payment for Restaurant Accounts; Modifications to the Service and Prices</h2>
            <p>The Company reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Accounts (or any part thereof) with or without notice.</p>
            <p>Payment for Accounts must be made in advance by direct debit, credit or debit card at the time of subscription of the Account. Any other payment arrangements must be made in advance between the User and an authorised Company representative. All fees paid to the Company for use of an Account are non-refundable.</p>
            <p>The User may be charged a fee for setup, custom development, SMS messages and the monthly fee in advance on first subscription and thereafter at a regularly recurring monthly billing cycle. All fees are subject to change without notice. The Restaurant is responsible for reviewing the Pricing Schedule and remaining aware of the fees charged by the Company. Unless a cancellation notice is received by the Company in writing, or through the account management options on the Sites prior to the start of the next billing cycle of the Account, an Account will automatically renew for the next month. By agreeing to these Terms of Service, the User authorises the Company to charge the monthly renewal amount by credit card or electronic funds transfer for the Account on the relevant anniversary date in advance of each monthly billing cycle, or the next business day available.</p>
            <p>In the event that a recurring credit charge or direct debit facility is cancelled by the Restaurant or authorised person or a payment request is declined for whatever reason, the Company reserves the right to levy an administration fee of last months additional reservations (when subscription plan is Basic) and SMS messages (if restaurant used)  plus VAT (or local currency equivalent). In instances such as above, the Company reserves the right to immediately disable an account until the administration fee is paid and the recurring charge facility is re-enabled.</p>

            <h3>Chapter VI</h3>
            <h2 className="feedback-title">Termination</h2>
            <p>The Company, in its sole discretion, has the right to suspend or terminate any User’s Account and refuse any and all current or future use of the Account, or any other service of the Company, at any time for any reason, including, but not limited to, violation of these Terms of Service. Such a termination of a User’s Account will result in the forfeiture and relinquishment of all content in said Account.</p>
            <p>Users may cancel their Accounts at any time by using the account management options or by submitting a request in writing to support@Nubisreservation.com Thirty (30) days notice is required when cancelling. Accounts will be charged a full month if not notified in time.</p>
            <p>The Company may delete any of a User’s archived data within thirty (30) days after the date of termination.</p>

            <h4 className="feedback-sub_title">Indemnification</h4>
            <p>All Users agree to indemnify and hold the Company, its subsidiaries, affiliates, officers and employees, and service providers harmless from any claim or demand, including reasonable legal fees, made by any third party due to or arising out of a User’s use of the Sites, the User’s violation of this Agreement, or the User’s infringement of any intellectual property or other right of any person or entity. Even though prohibited, people may provide information that is offensive, false, harmful, or deceptive. The Company assumes no responsibility or liability whatsoever for such content or actions.</p>

            <h3>Chapter VII</h3>
            <h2 className="feedback-title">Limitation of Liability</h2>
            <p>UNDER NO CIRCUMSTANCES WILL THE COMPANY BE LIABLE FOR ANY INJURIES, DEATH, LOSS OR DAMAGE CAUSED BY YOUR USE OF THE SITE, INCLUDING ANY SOFTWARE, MATERIALS, CONTENT, FOOD, PRODUCTS AND/OR SERVICES PROVIDED OR USE OR RELIANCE ON INFORMATION OBTAINED THROUGH THIS SITE. IT IS YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS, OR USEFULNESS OF THIS SITE AND THE RESOURCES, MATERIALS, CONTENT AND SOFTWARE PROVIDED THEREIN. IN NO EVENT SHALL THE COMPANY BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR RELATING TO THE SITE OR THIS AGREEMENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR NEGLIGENCE, CONSEQUENTIAL, INCIDENTAL OR OTHER DAMAGES, IN SUCH JURISDICTIONS THE COMPANY’S LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THIS WEBSITE IS TO STOP USING THIS WEBSITE.</p>

            <h4 className="feedback-sub_title">Disclaimer of Warranties</h4>
            <p>YOU ACKNOWLEDGE AND AGREE THAT THIS SITE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. NONE OF THE COMPANY, ITS AFFILIATES, SUBSIDIARIES OR ITS OR THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS (COLLECTIVELY THE “COMPANY PARTIES”) GUARANTEES THE ACCURACY, COMPLETENESS, TIMELINESS, RELIABILITY, SUITABILITY OR USEFULNESS OF ANY PORTION OF THE SITE. NONE OF THE COMPANY PARTIES WARRANT THAT THIS WEBSITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SPECIFIC INFORMATION THAT IS REQUESTED WILL BE PROVIDED OR THAT THIS SITE OR ITS SERVER(S) ARE OR WILL BE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL ELEMENTS. YOU EXPRESSLY AGREE THAT THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THIS SITE AND THE ACCURACY, TIMELINESS OR COMPLETENESS OF THE CONTENT OR SERVICES IS ASSUMED SOLELY BY YOU.</p>
            <p>NONE OF THE COMPANY PARTIES MAKE ANY, AND HEREBY SPECIFICALLY DISCLAIM ANY AND ALL, REPRESENTATIONS, ENDORSEMENTS, GUARANTEES, AND WARRANTIES, EXPRESSED OR IMPLIED, REGARDING THIS SITE AND ANY OF THE INFORMATION, SOFTWARE AND OTHER MATERIALS THEREIN, INCLUDING WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. YOU UNDERSTAND AND AGREE THAT ANY CONTENT, SOFTWARE, MATERIALS AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE IS USED AT YOUR OWN RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH CONTENT, MATERIALS AND/OR DATA.</p>
            <p>The Users expressly understand and agree that the Company shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if the Company has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the service; (ii) the cost of procurement of substitute food, goods and services resulting from any food, goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the service; (iii) unauthorized access to or alteration of the Users’ transmissions or data; (iv) statements or conduct of any third party on the service; (v) termination of the Users’ Accounts; or (vi) any other matter relating to the Accounts. In the event that notwithstanding the foregoing, the Company is found liable to a User for damages from any cause whatsoever, and regardless of the form of the action (whether in contract, tort (including negligence), product liability or otherwise), the liability of the Company to the User will be limited to the amount that the User paid for his/her/its Account.</p>

            <h3>Chapter VIII</h3>
            <h2 className="feedback-title">General Conditions</h2>
            <p>The User agrees that their use of the Accounts is at their sole risk. The service is provided on an “as is” and “as available” basis.
            The User must not modify, adapt or hack the Accounts or modify another website so as to falsely imply that it is associated with the Accounts, the Company, or any other Company service.</p>
            <p>The User agrees not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Accounts, use of the Accounts, or access to the Accounts without the express written permission of the Company.</p>
            <p>The Company may, but have no obligation to, remove content, and Accounts containing content, that it determines in its sole discretion to be unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any intellectual property rights or these Terms of Service.</p>
            <p>Verbal, physical, written or other abuse (including threats of abuse or retribution) of any Company customer, employee, member, or officer will result in immediate Account termination.</p>
            <p>The User understands that the technical processing and transmission of the Accounts, including their content, may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
            <p>The User must not upload, post, host, or transmit unsolicited email, SMS, or “spam” messages.</p>
            <p>The User must not transmit any worms or viruses or any code of a destructive nature. The Company does not warrant that (i) the Accounts will meet the User’s specific requirements, (ii) the Accounts will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the Accounts will be accurate or reliable, (iv) the quality of any food, products, services, information, or other material purchased or obtained by the Users through the Site will meet their expectations, and (v) any errors in the Accounts will be corrected.</p>
            <p>The failure of the Company to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service constitutes the entire agreement between the Users and the Company and govern the use of the Accounts, superseding any prior agreements between the Users and the Company (including, but not limited to, any prior versions of the Terms of Service).</p>
            <p>Unless otherwise provided, the Terms of Service shall be governed by the laws of the Danish law without effect to its conflict of laws provisions. Claims, disputes or other matters in question between the parties to the Terms of Service arising out of or relating to the Terms of Service or the breach thereof shall be subject to and decided by binding arbitration in accordance with the rules of the danish court currently in effect unless the parties mutually agree otherwise. No arbitration arising out of or relating to the Terms of Service shall include, by consolidation, joinder or in any other manner, an additional person or entity not a party to the Terms of Service, except by written consent of the Users, the Company and any other person or entity sought to be joined. Consent to an arbitration involving an additional person or entity shall not constitute consent to arbitration of any claim, dispute or other matter in question not described in the written consent. The agreement to arbitrate shall be specifically enforceable in accordance with applicable law in any court having jurisdiction thereof. The award rendered by the arbitrator or arbitrators shall be binding and final, and judgment may be entered upon it in accordance with applicable law in any court having jurisdiction thereof. The parties agree that in the event any such dispute proceeds to arbitration, the prevailing party will be entitled to recover, as part of the arbitration award, its reasonable attorneys’ fees and costs incurred in the arbitration, at the discretion of the arbitrator. Said arbitration shall be held in Kaunas, Lithuania unless a different location is agreed to in writing by all parties.</p>
            <p>If any term of the Terms of Service is deemed unenforceable or invalid by a tribunal with valid jurisdiction then the finding of unenforceability or invalidity of that part shall not affect the remaining portions of the Terms of Service which shall remain in fall force and effect.</p>
            <p>The Terms of Service and all of its terms and provisions are binding upon the heirs and personal representatives of the Users and the successors and assignees of the Company; provided, however, no assignment by the Users of their rights and/or interests in and to these TeLIABILITY</p>
            <p>Your use of and browsing in this Website is at your own risk. Nubis reservation does not warrant that the software used on this Website and the information, on-line applications or any other service provided by means of this site are error-free or that the use of them will be uninterrupted. Nubis reservation expressly disclaims any liability for the above, including for example for accuracy, condition, merchantability and fitness for a particular purpose. Notwithstanding anything to the contrary contained on this Website, Nubis reservation is in no way liable for any loss of profit, revenue or any form whatsoever. Nubi's reservation form for indirect damages arising out of or in connection with this Website or the use of any of the services listed on this Website.
              Questions about the Terms of Service should be sent to info@Nubisreservation.com</p>
          </div>


        </div>
      </div>
    </Suspense>
  );
}

export default App;

if (document.getElementById('app')) {
  ReactDOM.render(<App />, document.getElementById('app'));
}
